# Generated by Django 4.2.7 on 2025-12-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeleniumDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('driver_type', models.CharField(choices=[('CHROME', 'Chrome'), ('FIREFOX', 'Firefox'), ('EDGE', 'Edge')], default='CHROME', max_length=10)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='selenium_app.seleniumdriver')),
            ],
        ),
        migrations.CreateModel(
            name='CrawlRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('requester', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('QUEUED', 'Queued')], default='PENDING', max_length=10)),
                ('html_content', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='selenium_app.seleniumdriver')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_id'], name='selenium_ap_request_a3133c_idx'), models.Index(fields=['status'], name='selenium_ap_status_500066_idx'), models.Index(fields=['created_at'], name='selenium_ap_created_7009c9_idx')],
            },
        ),
    ]
