# Generated by Django 4.2.7 on 2025-11-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selenium_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='selenium_app.seleniumdriver'),
        ),
        migrations.AlterField(
            model_name='crawlrequest',
            name='requester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
