# Generated by Django 4.2.7 on 2025-12-04 09:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تأیید')),
                ('verification_code_expires', models.DateTimeField(blank=True, null=True, verbose_name='انقضای کد تأیید')),
                ('password_reset_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='توکن بازیابی')),
                ('password_reset_expires', models.DateTimeField(blank=True, null=True, verbose_name='انقضای توکن بازیابی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'custom_users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('internal', 'نماینده داخلی'), ('external', 'نماینده خارجی')], default='external', max_length=10, verbose_name='نوع نماینده')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام شرکت/نماینده')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='تلفن تماس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='نرخ کمیسیون (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agents', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
            ],
            options={
                'verbose_name': 'پروفایل نماینده',
                'verbose_name_plural': 'پروفایل\u200cهای نماینده',
                'db_table': 'agent_profiles',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='آیدی تلگرام')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کاربری تلگرام')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد زبان')),
                ('is_premium', models.BooleanField(default=False, verbose_name='پریمیوم')),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='آدرس عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل تلگرام',
                'verbose_name_plural': 'پروفایل\u200cهای تلگرام',
                'db_table': 'telegram_profiles',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='تلفن تماس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وبسایت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه مالیاتی')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('rating', models.FloatField(default=0.0, verbose_name='امتیاز')),
                ('total_contracts', models.IntegerField(default=0, verbose_name='تعداد قراردادها')),
                ('completed_contracts', models.IntegerField(default=0, verbose_name='قراردادهای تکمیل شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sellers', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sellers_profiles', to='auth_app.agentprofile', verbose_name='نماینده اختصاصی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل فروشنده',
                'verbose_name_plural': 'پروفایل\u200cهای فروشنده',
                'db_table': 'seller_profiles',
            },
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_profile_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک پروفایل آمازون')),
                ('amazon_reviews_count', models.IntegerField(default=0, verbose_name='تعداد ریویوهای آمازون')),
                ('amazon_purchases_count', models.IntegerField(default=0, verbose_name='تعداد خریدهای آمازون')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('total_purchases', models.IntegerField(default=0, verbose_name='تعداد خریدها')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مجموع هزینه\u200cها')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='نرخ موفقیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_buyers', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buyers', to='auth_app.agentprofile', verbose_name='نماینده اختصاصی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل خریدار',
                'verbose_name_plural': 'پروفایل\u200cهای خریدار',
                'db_table': 'buyer_profiles',
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='managed_sellers',
            field=models.ManyToManyField(blank=True, related_name='managed_by_agents', to='auth_app.sellerprofile', verbose_name='فروشندگان تحت مدیریت'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'سوپر ادمین'), ('admin', 'ادمین')], default='admin', max_length=20, verbose_name='نقش')),
                ('can_manage_users', models.BooleanField(default=True, verbose_name='مدیریت کاربران')),
                ('can_manage_products', models.BooleanField(default=True, verbose_name='مدیریت محصولات')),
                ('can_manage_contracts', models.BooleanField(default=True, verbose_name='مدیریت قراردادها')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='مدیریت تنظیمات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل ادمین',
                'verbose_name_plural': 'پروفایل\u200cهای ادمین',
                'db_table': 'admin_profiles',
            },
        ),
    ]
