# Generated by Django 4.2.7 on 2025-11-30 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل کاربر')),
                ('people', models.TextField(blank=True, null=True, verbose_name='پیپل کاربر')),
                ('amazon_profile_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک پروفایل آمازون')),
                ('amazon_reviews_count', models.IntegerField(default=0, verbose_name='تعداد ریویوهای آمازون')),
                ('amazon_purchases_count', models.IntegerField(default=0, verbose_name='تعداد خریدهای آمازون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Profile',
                'verbose_name_plural': 'Telegram Profiles',
                'db_table': 'telegram_profiles',
            },
        ),
    ]
