# Generated by Django 4.2.7 on 2025-11-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='amazon_profile_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک پروفایل آمازون'),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='amazon_purchases_count',
            field=models.IntegerField(default=0, verbose_name='تعداد خریدهای آمازون'),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='amazon_reviews_count',
            field=models.IntegerField(default=0, verbose_name='تعداد ریویوهای آمازون'),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل کاربر'),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='people',
            field=models.TextField(blank=True, null=True, verbose_name='پیپل کاربر'),
        ),
    ]
