# Generated by Django 4.2.7 on 2025-11-30 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageEditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_message_text', models.TextField(verbose_name='Old Message Text')),
                ('new_message_text', models.TextField(verbose_name='New Message Text')),
                ('old_images', models.JSONField(default=list, verbose_name='Old Images')),
                ('new_images', models.JSONField(default=list, verbose_name='New Images')),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('telegram_edit_success', models.BooleanField(default=False, verbose_name='Telegram Edit Success')),
            ],
            options={
                'verbose_name': 'Message Edit History',
                'verbose_name_plural': 'Message Edit History',
                'db_table': 'telegram_message_histories',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageSendingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('response_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Message Sending Log',
                'verbose_name_plural': 'Message Sending Logs',
                'db_table': 'telegram_message_sending_logs',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Channel Name')),
                ('username', models.CharField(blank=True, help_text='@channel_username', max_length=255, null=True, unique=True, verbose_name='Channel Username')),
                ('channel_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Channel ID')),
                ('country', models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('IR', 'Iran'), ('TR', 'Turkey'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia')], max_length=2, verbose_name='Country')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='channel_logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Telegram Channels',
                'db_table': 'telegram_channels',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_text', models.TextField(verbose_name='Message Text')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs as JSON', verbose_name='Images List')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Message ID')),
                ('reply_to_message_id', models.BigIntegerField(blank=True, help_text='Telegram message ID to reply to (optional)', null=True, verbose_name='Reply to Message ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('edited', 'Edited')], default='draft', max_length=20, verbose_name='Status')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Time')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_manager.telegramchannel', verbose_name='Channel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Telegram Message',
                'verbose_name_plural': 'Telegram Messages',
                'db_table': 'telegram_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='telegramchannel',
            constraint=models.CheckConstraint(check=models.Q(('username__isnull', False), ('channel_id__isnull', False), _connector='OR'), name='at_least_one_identifier'),
        ),
        migrations.AddField(
            model_name='messagesendinglog',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_logs', to='telegram_manager.telegrammessage'),
        ),
        migrations.AddField(
            model_name='messageedithistory',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Edited By'),
        ),
        migrations.AddField(
            model_name='messageedithistory',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='telegram_manager.telegrammessage'),
        ),
    ]
