# Generated by Django 4.2.7 on 2025-11-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='channel_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Channel ID'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='username',
            field=models.CharField(blank=True, help_text='@channel_username', max_length=255, null=True, unique=True, verbose_name='Channel Username'),
        ),
        migrations.AddConstraint(
            model_name='telegramchannel',
            constraint=models.CheckConstraint(check=models.Q(('username__isnull', False), ('channel_id__isnull', False), _connector='OR'), name='at_least_one_identifier'),
        ),
    ]
