# Generated by Django 4.2.7 on 2025-11-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_manager', '0002_alter_telegramchannel_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesendinglog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
