# Generated by Django 4.2.7 on 2025-11-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_manager', '0003_alter_messagesendinglog_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='reply_to_message',
            field=models.ForeignKey(blank=True, help_text='Select if this is a reply to another message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_manager.telegrammessage', verbose_name='Reply To Message'),
        ),
    ]
