# Generated by Django 4.2.7 on 2025-11-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_manager', '0004_telegrammessage_reply_to_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammessage',
            name='reply_to_message',
        ),
    ]
