# Generated by Django 4.2.7 on 2025-11-26 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('product_url', models.URLField(blank=True, max_length=500)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('RENEWED', 'Renewed'), ('REFURBISHED', 'Refurbished')], default='NEW', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'amazon_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('asins_crawled', models.JSONField(default=list)),
                ('total_products', models.IntegerField(default=0)),
                ('successful_crawls', models.IntegerField(default=0)),
                ('failed_crawls', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'crawl_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3)),
                ('seller', models.CharField(blank=True, max_length=200)),
                ('seller_type', models.CharField(blank=True, max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('stock_status', models.CharField(blank=True, max_length=100)),
                ('shipping_info', models.TextField(blank=True)),
                ('crawl_source', models.CharField(max_length=100)),
                ('crawl_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='amazon_app.amazonproduct')),
            ],
            options={
                'db_table': 'product_prices',
                'ordering': ['-crawl_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='amazonproduct',
            index=models.Index(fields=['asin'], name='amazon_prod_asin_7665c3_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproduct',
            index=models.Index(fields=['brand'], name='amazon_prod_brand_625d15_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproduct',
            index=models.Index(fields=['category'], name='amazon_prod_categor_0e225c_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproduct',
            index=models.Index(fields=['rating'], name='amazon_prod_rating_592cde_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'crawl_timestamp'], name='product_pri_product_e3510d_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['crawl_timestamp'], name='product_pri_crawl_t_3f1baa_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['price'], name='product_pri_price_c01342_idx'),
        ),
    ]
