# Generated by Django 4.2.7 on 2025-11-30 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCrawlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='Session ID')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('country_code', models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('CA', 'Canada'), ('JP', 'Japan'), ('AU', 'Australia')], default='US', max_length=2, verbose_name='Country Code')),
                ('asins_crawled', models.JSONField(default=list, verbose_name='ASINs Crawled')),
                ('total_products', models.IntegerField(default=0, verbose_name='Total Products')),
                ('successful_crawls', models.IntegerField(default=0, verbose_name='Successful Crawls')),
                ('failed_crawls', models.IntegerField(default=0, verbose_name='Failed Crawls')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='PENDING', max_length=10, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('error_log', models.TextField(blank=True, verbose_name='Error Log')),
            ],
            options={
                'db_table': 'amazon_crawl_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=10, verbose_name='ASIN')),
                ('country_code', models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('CA', 'Canada'), ('JP', 'Japan'), ('AU', 'Australia')], default='US', max_length=2, verbose_name='Country Code')),
                ('title', models.TextField(verbose_name='Product Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Brand')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Manufacturer')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Category')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Image URL')),
                ('product_url', models.URLField(blank=True, max_length=500, verbose_name='Product URL')),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('RENEWED', 'Renewed'), ('REFURBISHED', 'Refurbished')], default='NEW', max_length=20, verbose_name='Condition')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Features')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Specifications')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rating')),
                ('review_count', models.IntegerField(default=0, verbose_name='Review Count')),
                ('variants', models.JSONField(blank=True, default=list, verbose_name='Variants')),
                ('domain', models.CharField(default='amazon.com', max_length=50, verbose_name='Amazon Domain')),
                ('geo_location', models.JSONField(blank=True, default=dict, verbose_name='Geo Location')),
                ('seller', models.CharField(blank=True, max_length=200, verbose_name='Seller')),
                ('seller_id', models.CharField(blank=True, max_length=50, verbose_name='Seller ID')),
                ('seller_type', models.CharField(blank=True, max_length=50, verbose_name='Seller Type')),
                ('seller_info', models.JSONField(blank=True, default=dict, verbose_name='Seller Information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_crawled', models.DateTimeField(blank=True, null=True, verbose_name='Last Crawled')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'amazon_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmazonProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen')], default='USD', max_length=3, verbose_name='Currency')),
                ('country_code', models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('CA', 'Canada'), ('JP', 'Japan'), ('AU', 'Australia')], default='US', max_length=2, verbose_name='Country Code')),
                ('seller', models.CharField(blank=True, max_length=200, verbose_name='Seller')),
                ('seller_type', models.CharField(blank=True, max_length=50, verbose_name='Seller Type')),
                ('availability', models.BooleanField(default=True, verbose_name='Availability')),
                ('stock_status', models.CharField(blank=True, max_length=100, verbose_name='Stock Status')),
                ('shipping_info', models.TextField(blank=True, verbose_name='Shipping Info')),
                ('delivery_date', models.CharField(blank=True, max_length=100, verbose_name='Delivery Date')),
                ('crawl_source', models.CharField(max_length=100, verbose_name='Crawl Source')),
                ('crawl_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Crawl Timestamp')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='amazon_app.amazonproduct', verbose_name='Product')),
            ],
            options={
                'db_table': 'amazon_product_prices',
                'ordering': ['-crawl_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='amazonproduct',
            index=models.Index(fields=['asin', 'country_code'], name='amazon_prod_asin_115a87_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproduct',
            index=models.Index(fields=['country_code'], name='amazon_prod_country_04e414_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproduct',
            index=models.Index(fields=['brand'], name='amazon_prod_brand_625d15_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproduct',
            index=models.Index(fields=['category'], name='amazon_prod_categor_0e225c_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproduct',
            index=models.Index(fields=['rating'], name='amazon_prod_rating_592cde_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproduct',
            index=models.Index(fields=['seller'], name='amazon_prod_seller_c094a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='amazonproduct',
            unique_together={('asin', 'country_code')},
        ),
        migrations.AddIndex(
            model_name='amazonproductprice',
            index=models.Index(fields=['product', 'crawl_timestamp'], name='amazon_prod_product_312f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproductprice',
            index=models.Index(fields=['country_code', 'crawl_timestamp'], name='amazon_prod_country_a5904f_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproductprice',
            index=models.Index(fields=['crawl_timestamp'], name='amazon_prod_crawl_t_da9380_idx'),
        ),
        migrations.AddIndex(
            model_name='amazonproductprice',
            index=models.Index(fields=['price'], name='amazon_prod_price_440f4b_idx'),
        ),
    ]
