# Generated by Django 4.2.7 on 2025-11-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrawlSession',
            new_name='AmazonCrawlSession',
        ),
        migrations.RenameModel(
            old_name='ProductPrice',
            new_name='AmazonProductPrice',
        ),
        migrations.RenameIndex(
            model_name='amazonproductprice',
            new_name='amazon_prod_product_312f4b_idx',
            old_name='product_pri_product_e3510d_idx',
        ),
        migrations.RenameIndex(
            model_name='amazonproductprice',
            new_name='amazon_prod_crawl_t_da9380_idx',
            old_name='product_pri_crawl_t_3f1baa_idx',
        ),
        migrations.RenameIndex(
            model_name='amazonproductprice',
            new_name='amazon_prod_price_440f4b_idx',
            old_name='product_pri_price_c01342_idx',
        ),
        migrations.AlterModelTable(
            name='amazoncrawlsession',
            table='amazon_crawl_sessions',
        ),
        migrations.AlterModelTable(
            name='amazonproductprice',
            table='amazon_product_prices',
        ),
    ]
