# Generated by Django 4.2.7 on 2025-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0002_rename_crawlsession_amazoncrawlsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproductprice',
            name='variants',
            field=models.JSONField(blank=True, default=list, help_text='Variant ASINs and their data in JSON format'),
        ),
    ]
