# Generated by Django 4.2.7 on 2025-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0003_amazonproductprice_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonproductprice',
            name='variants',
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='variants',
            field=models.JSONField(blank=True, default=list, help_text='Variant ASINs and their data in JSON format'),
        ),
    ]
