# Generated by Django 4.2.7 on 2025-11-30 14:54

import contract_manager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('review', 'Register Review'), ('rating_5', 'Register 5-Star Rating'), ('rating_4_plus', 'Register 4+ Star Rating'), ('photo', 'Register Photo'), ('video', 'Register Video'), ('seller_feedback', 'Register Seller Feedback')], max_length=50, unique=True, verbose_name='Action Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Action Type',
                'verbose_name_plural': 'Action Types',
                'db_table': 'contract_action_type',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('IR', 'Iran'), ('TR', 'Turkey'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('CN', 'China'), ('JP', 'Japan'), ('KR', 'South Korea'), ('IN', 'India'), ('BR', 'Brazil'), ('CA', 'Canada'), ('AU', 'Australia'), ('NL', 'Netherlands'), ('SE', 'Sweden')], max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='Country Code')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('native_name', models.CharField(blank=True, max_length=100, verbose_name='Native Name')),
                ('icon', models.ImageField(blank=True, help_text='آیکون کوچک برای کشور', null=True, upload_to=contract_manager.models.country_icon_upload_path, verbose_name='Country Icon')),
                ('flag', models.ImageField(blank=True, help_text='پرچم ملی کشور', null=True, upload_to=contract_manager.models.country_flag_upload_path, verbose_name='Country Flag')),
                ('amazon_domain', models.CharField(default='amazon.com', help_text='مثال: amazon.com, amazon.co.uk, amazon.de', max_length=50, verbose_name='Amazon Domain')),
                ('amazon_url', models.URLField(blank=True, help_text='URL پایه آمازون در این کشور', verbose_name='Amazon Base URL')),
                ('timezone', models.CharField(default='UTC', help_text='مثال: America/New_York, Europe/London', max_length=50, verbose_name='Timezone')),
                ('language', models.CharField(default='en', help_text='مثال: en, de, fr, es', max_length=10, verbose_name='Language Code')),
                ('default_zip_code', models.CharField(blank=True, help_text='کد پستی پیش\u200cفرض برای تنظیم موقعیت در آمازون', max_length=20, verbose_name='Default ZIP Code')),
                ('default_city', models.CharField(blank=True, help_text='شهر پیش\u200cفرض برای تنظیم موقعیت', max_length=100, verbose_name='Default City')),
                ('default_state', models.CharField(blank=True, help_text='استان پیش\u200cفرض برای تنظیم موقعیت', max_length=100, verbose_name='Default State')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_available_for_products', models.BooleanField(default=True, verbose_name='Available for Products')),
                ('is_available_for_crawling', models.BooleanField(default=True, verbose_name='Available for Crawling')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=100, verbose_name='Currency Name')),
                ('exchange_rate_to_cny', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Exchange Rate to CNY')),
                ('symbol', models.CharField(blank=True, max_length=5, verbose_name='Symbol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asin', models.CharField(max_length=10, unique=True, verbose_name='ASIN')),
                ('variant_asins', models.TextField(blank=True, help_text='Comma-separated list of variant ASINs', verbose_name='Variant ASINs')),
                ('title', models.CharField(max_length=500, verbose_name='Product Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('search_guide', models.TextField(blank=True, verbose_name='Search Guide')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('daily_max_quantity', models.IntegerField(default=10, verbose_name='Daily Max Quantity')),
                ('total_max_quantity', models.IntegerField(default=100, verbose_name='Total Max Quantity')),
                ('current_quantity', models.IntegerField(default=0, verbose_name='Current Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_stopped', models.BooleanField(default=False, verbose_name='Stopped')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon_app.amazonproduct', verbose_name='Amazon Product Data')),
                ('country', models.ForeignKey(limit_choices_to={'is_available_for_products': True}, on_delete=django.db.models.deletion.CASCADE, to='contract_manager.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'contract_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(choices=[('seller', 'Seller'), ('agent', 'Agent')], max_length=10, verbose_name='Seller Type')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'db_table': 'contract_seller',
            },
        ),
        migrations.CreateModel(
            name='ProductTelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.product', verbose_name='Product')),
                ('telegram_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_manager.telegrammessage', verbose_name='Telegram Message')),
            ],
            options={
                'verbose_name': 'Product Telegram Message',
                'verbose_name_plural': 'Product Telegram Messages',
                'db_table': 'contract_product_telegram_message',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.seller', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='country',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='ارز پیش\u200cفرض برای این کشور', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract_manager.currency', verbose_name='Default Currency'),
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of product price to refund', max_digits=5, verbose_name='Refund Percentage')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Commission Amount')),
                ('refund_description', models.TextField(verbose_name='Refund Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.actiontype', verbose_name='Action Type')),
                ('commission_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.currency', verbose_name='Commission Currency')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.seller', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Contract Template',
                'verbose_name_plural': 'Contract Templates',
                'db_table': 'contract_template',
                'unique_together': {('seller', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='ProductContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_refund_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Custom Refund Percentage')),
                ('custom_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custom Commission Amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.contracttemplate', verbose_name='Contract Template')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Contract',
                'verbose_name_plural': 'Product Contracts',
                'db_table': 'contract_product_action_contract',
                'unique_together': {('product', 'contract_template')},
            },
        ),
        migrations.CreateModel(
            name='CountryChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Channel')),
                ('priority', models.IntegerField(default=1, help_text='Lower number = higher priority', verbose_name='Priority')),
                ('auto_send_new_products', models.BooleanField(default=True, verbose_name='Auto Send New Products')),
                ('send_product_updates', models.BooleanField(default=True, verbose_name='Send Product Updates')),
                ('send_price_alerts', models.BooleanField(default=False, verbose_name='Send Price Alerts')),
                ('message_template', models.TextField(blank=True, help_text='Custom template for product messages. Use {{variable}} for placeholders.', verbose_name='Custom Message Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_manager.telegramchannel', verbose_name='Telegram Channel')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country Channel Configuration',
                'verbose_name_plural': 'Country Channel Configurations',
                'db_table': 'contract_country_channel_config',
                'ordering': ['country', 'priority'],
                'unique_together': {('country', 'channel')},
            },
        ),
    ]
