# Generated by Django 4.2.7 on 2025-12-01 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Message ID')),
                ('telegram_message_text', models.TextField(verbose_name='Telegram Message Text')),
                ('telegram_images', models.JSONField(default=list, help_text='لیست URL عکس\u200cها', verbose_name='Telegram Images')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent', 'Sent'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='draft', max_length=20, verbose_name='Status')),
                ('should_send', models.BooleanField(default=True, verbose_name='Should Send to Channel')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Edited At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('view_count', models.IntegerField(default=0, verbose_name='View Count')),
                ('click_count', models.IntegerField(default=0, verbose_name='Click Count')),
                ('error_log', models.TextField(blank=True, verbose_name='Error Log')),
                ('auto_update', models.BooleanField(default=True, verbose_name='Auto Update Message')),
                ('notify_on_change', models.BooleanField(default=True, verbose_name='Notify on Product Change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_manager.telegramchannel', verbose_name='Telegram Channel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Channel',
                'verbose_name_plural': 'Product Channels',
                'db_table': 'contract_product_channel',
                'ordering': ['-sent_at'],
                'unique_together': {('product', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='ProductUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('price_change', 'Price Change'), ('stock_change', 'Stock Change'), ('info_update', 'Information Update'), ('status_change', 'Status Change'), ('telegram_update', 'Telegram Message Update'), ('channel_update', 'Channel Status Update')], max_length=50, verbose_name='Update Type')),
                ('old_data', models.JSONField(default=dict, verbose_name='Old Data')),
                ('new_data', models.JSONField(default=dict, verbose_name='New Data')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('affected_channels', models.JSONField(default=list, verbose_name='Affected Channels')),
                ('telegram_updates_sent', models.BooleanField(default=False, verbose_name='Telegram Updates Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_manager.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Update Log',
                'verbose_name_plural': 'Product Update Logs',
                'db_table': 'contract_product_update_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProductTelegramMessage',
        ),
    ]
